/**
 * Central trait schema — every visual parameter of the cat lives here. Edit and
 * rebuild; values are baked into the bundle.
 *
 * Every tunable value is declared with one of four constructors:
 *
 *   c(value, min, max, step)   fixed config value — a slider in the trait lab
 *   d(min, max)                seed-generated — sampled uniformly per cat
 *   pick(options, pinned?)     categorical — seed-picked uniformly, or pinned
 *   pickW({a: w, …}, pinned?)  categorical — seed-picked by weight, or pinned
 *
 * Flip a value between fixed and generated by swapping (or adding the pinned
 * argument to) its constructor; nothing else needs to change. Each generated
 * param samples an independent hash of its dot-path and the seed, so adding,
 * removing, or pinning one never affects the others. The trait lab auto-discovers
 * all params from this schema.
 *
 * THE ONE RULE: bounded parametric variation around a fixed template. The seed
 * only ever feeds MULTIPLIERS with hand-tuned floor/ceiling — never raw
 * coordinates — so even extreme seeds give a chonky-but-correct cat, never a
 * broken one. Every scalar resolves as `min + rng() * (max - min)`, clamped by
 * its own declared range.
 *
 * Units, unless stated otherwise:
 *   hues                          degrees 0–360
 *   saturation / lightness        0–1
 *   sizes / multipliers           dimensionless scale factors around 1.0
 */

import { sampleUnit } from './random';
import { hslHex, Palette } from './color';

// ── Parameter constructors ────────────────────────────────────────────────────

/** A scalar declared with its mode and range. The schema is a tree of these. */
export interface ScalarParam {
  readonly mode:  'config' | 'dna';
  readonly value: number;   // fixed value ('config') or range midpoint ('dna')
  readonly min:   number;
  readonly max:   number;
  readonly step:  number;
}

/** Fixed value, tunable in the trait lab. */
function c(value: number, min: number, max: number, step: number): ScalarParam {
  return { mode: 'config', value, min, max, step };
}

/** Seed-generated: sampled uniformly from [min, max] for each cat. */
function d(min: number, max: number): ScalarParam {
  return { mode: 'dna', value: (min + max) / 2, min, max, step: (max - min) / 100 };
}

/**
 * A categorical choice. `options` is read lazily so it can come from a registry
 * still populating at declaration time. `weights`, when present, biases the
 * seed pick toward heavier options (parallel to `options`).
 */
export interface ChoiceParam {
  readonly mode:     'config' | 'dna';
  readonly value:    string | null;   // the pinned choice, or null when seed-picked
  readonly options:  () => string[];
  readonly weights?: number[];
}

/** Seed-picked choice from a list (uniform) — pass `pinned` to fix it instead. */
function pick(options: () => string[], pinned?: string): ChoiceParam {
  return { mode: pinned === undefined ? 'dna' : 'config', value: pinned ?? null, options };
}

/** Seed-picked choice with per-option weights — pass `pinned` to fix it instead. */
function pickW(weighted: Record<string, number>, pinned?: string): ChoiceParam {
  const names   = Object.keys(weighted);
  const weights = Object.values(weighted);
  return { mode: pinned === undefined ? 'dna' : 'config', value: pinned ?? null, options: () => names, weights };
}

// ── Schema ────────────────────────────────────────────────────────────────────

export const config = {
  coat: {
    // Weighted so common coats dominate and the showy ones stay rare.
    pattern:    pickW({ solid: 22, tabby: 26, tuxedo: 16, bicolor: 12, calico: 10, pointed: 8, spotted: 6 }),
    hue:        d(0, 360),       // the main anti-collision axis — continuous
    saturation: d(0.30, 0.82),
    lightness:  d(0.40, 0.66),
    // Rare off-palette cat: when 'on', the palette widens to vivid, unusual colour.
    fantasy:    pickW({ off: 95, on: 5 }),
  },

  build: {
    chonk: d(0.80, 1.42),   // body width multiplier — exposed as a meter
  },

  head: {
    size: d(0.88, 1.14),
  },

  ear: {
    size: d(0.82, 1.22),
    tilt: d(-0.16, 0.30),   // outward splay, radians-ish
  },

  eye: {
    size:          d(0.78, 1.28),
    squint:        d(0, 1),         // 0 = round, 1 = sleepy slit
    hue:           d(35, 215),      // amber → green → blue; fantasy widens it
    // ~6% of cats: the second eye takes a different hue.
    heterochromia: pickW({ off: 94, on: 6 }),
  },

  tail: {
    curl: d(0, 1),
  },

  // Affects mouth / eyes / tongue.
  mood: pickW({ content: 40, sleepy: 24, grumpy: 20, blep: 16 }),
};

/**
 * The raw schema tree — the structure of `configSchema` at import time. Fields
 * are still wrapped in `ScalarParam` / `ChoiceParam` objects carrying metadata
 * (min, max, step, mode, weights). Use this type when you need to *inspect* the
 * schema: walking its tree, reading ranges, building a config UI, etc.
 */
export type CatsumSchema = typeof config;

// ── Derived data (computed from resolved traits, not sampled) ───────────────────

/** A display name and a breed archetype, both derived from the seed. */
export interface Specimen {
  name:  string;
  breed: string;
}

// ── Type machinery ──────────────────────────────────────────────────────────

type Resolved<T> =
  T extends ScalarParam ? number
  : T extends ChoiceParam ? string
  : T extends readonly unknown[] ? T
  : T extends object ? { [K in keyof T]: Resolved<T[K]> }
  : T;

/** The resolved trait tree — every knob unwrapped to its plain value. */
export type ResolvedTraits = Resolved<CatsumSchema>;

/**
 * A cat's fully-resolved config for a given seed: every trait unwrapped, plus
 * the derived `colors` palette and `specimen` card (name / breed).
 * This is what the renderer works with and exposes on `.config`.
 */
export type CatsumConfig = ResolvedTraits & {
  colors:   Palette;
  specimen: Specimen;
};

/** Marker returned by `seeded()` — flips a parameter to seed-generated. */
export interface Seeded { readonly mode: 'dna'; }

/** Make a parameter seed-generated, overriding the schema default.
 *  Use it in an overrides tree, e.g. `{ eye: { hue: seeded() } }`. */
export function seeded(): Seeded { return { mode: 'dna' }; }

/** Override a scalar parameter.
 *  - plain number → pin it to that fixed value
 *  - `seeded()`   → make it seed-generated (even if the schema default was c()) */
export type ScalarOverride = number | Seeded;

/** Override a categorical (choice) parameter.
 *  - plain string → pin it to that choice
 *  - `seeded()`   → make it seed-picked (even if the schema default was pinned) */
export type ChoiceOverride = string | Seeded;

type SchemaOverride<T> =
  T extends ScalarParam ? ScalarOverride
  : T extends ChoiceParam ? ChoiceOverride
  : T extends readonly unknown[] ? T
  : T extends object ? { [K in keyof T]?: SchemaOverride<T[K]> }
  : T;

/**
 * What you pass to `new CatsumRenderer(seed, { config: … })` or `setConfig()`.
 * Same tree shape as the schema but every field is optional (deep partial). A
 * plain number/string pins a parameter to a fixed value; `seeded()` flips it
 * back to seed-generated — overriding the schema default either way.
 */
export type CatsumConfigOverrides = SchemaOverride<CatsumSchema>;

// ── Schema resolution ─────────────────────────────────────────────────────────

export function isScalarParam(v: unknown): v is ScalarParam {
  return typeof v === 'object' && v !== null && 'mode' in v && 'min' in v;
}

export function isChoiceParam(v: unknown): v is ChoiceParam {
  return typeof v === 'object' && v !== null && 'mode' in v && 'options' in v;
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/**
 * Apply overrides onto the schema tree. A plain number/string pins a parameter:
 * the value is fixed and the mode becomes 'config', even for d()/seed-picked
 * defaults — so `{ coat: { hue: 200 } }` makes every cat render with that hue.
 * A `seeded()` marker flips a parameter back to seed-generated.
 */
export function mergeSchema(overrides: CatsumConfigOverrides = {}): CatsumSchema {
  function merge<T extends object>(base: T, patch: Record<string, unknown>): T {
    const merged = { ...base } as Record<string, unknown>;
    for (const [key, value] of Object.entries(patch)) {
      if (value === undefined) continue;
      const baseValue = (base as Record<string, unknown>)[key];
      if (isScalarParam(baseValue)) {
        if (typeof value === 'number') {
          merged[key] = { ...baseValue, mode: 'config', value };
        } else if (isPlainObject(value) && value.mode === 'dna') {
          merged[key] = { ...baseValue, mode: 'dna' };
        }
      } else if (isChoiceParam(baseValue)) {
        if (typeof value === 'string') {
          merged[key] = { ...baseValue, mode: 'config', value };
        } else if (isPlainObject(value) && value.mode === 'dna') {
          merged[key] = { ...baseValue, mode: 'dna' };
        }
      } else if (isPlainObject(baseValue) && isPlainObject(value)) {
        merged[key] = merge(baseValue, value);
      } else {
        merged[key] = value;
      }
    }
    return merged as T;
  }
  return merge(config, overrides as Record<string, unknown>);
}

/** Weighted index pick from a unit draw; falls back to uniform without weights. */
function pickIndex(u: number, count: number, weights?: number[]): number {
  if (!weights || weights.length !== count) return Math.floor(u * count);
  const total = weights.reduce((a, b) => a + b, 0);
  let threshold = u * total;
  for (let i = 0; i < count; i++) {
    threshold -= weights[i];
    if (threshold < 0) return i;
  }
  return count - 1;
}

/**
 * Resolve a schema tree to plain trait values, then attach the derived palette
 * and specimen card. Fixed params collapse to their value; seed-generated ones
 * are sampled using the seed and the param's dot-path as the hash label. Without
 * a seed, generated params resolve to their range midpoint (or first option),
 * used for the exported defaults.
 */
export function resolveConfig(schema: CatsumSchema, seed?: string): CatsumConfig {
  function resolve(node: unknown, path: string): unknown {
    if (isScalarParam(node)) {
      return node.mode === 'dna' && seed !== undefined
        ? node.min + sampleUnit(seed, path) * (node.max - node.min)
        : node.value;
    }
    if (isChoiceParam(node)) {
      const options = node.options();
      if (node.mode === 'config' && node.value !== null && options.includes(node.value)) return node.value;
      return seed !== undefined
        ? options[pickIndex(sampleUnit(seed, path), options.length, node.weights)]
        : options[0];
    }
    if (Array.isArray(node)) return node;
    if (isPlainObject(node)) {
      const out: Record<string, unknown> = {};
      for (const [k, v] of Object.entries(node)) out[k] = resolve(v, path ? `${path}.${k}` : k);
      return out;
    }
    return node;
  }
  const traits = resolve(schema, '') as ResolvedTraits;
  return {
    ...traits,
    colors:   derivePalette(traits),
    specimen: deriveSpecimen(traits, seed ?? ''),
  };
}

// ── Derivation ──────────────────────────────────────────────────────────────

/** Build the whole colour palette from the coat hue and pattern. */
function derivePalette(t: ResolvedTraits): Palette {
  const hue = t.coat.hue;
  let sat = t.coat.saturation;
  let lit = t.coat.lightness;

  // Fantasy: push toward a vivid, off-palette colour.
  if (t.coat.fantasy === 'on') { sat = Math.min(1, sat + 0.35); lit = Math.min(0.7, lit + 0.06); }
  // Pointed coats read as pale bodies with dark extremities.
  if (t.coat.pattern === 'pointed') lit = Math.min(0.86, lit + 0.26);
  // Calico bodies are mostly white with placed patches.
  if (t.coat.pattern === 'calico') { sat = Math.min(sat, 0.18); lit = 0.9; }

  const eyeL = t.eye.hue;
  const eyeR = t.eye.heterochromia === 'on' ? (t.eye.hue + 140) % 360 : t.eye.hue;

  return {
    base:     hslHex(hue, sat, lit),
    hi:       hslHex(hue, sat * 0.85, Math.min(0.96, lit + 0.15)),
    lo:       hslHex(hue, Math.min(1, sat + 0.06), Math.max(0.08, lit - 0.13)),
    edge:     hslHex(hue, sat * 0.55, Math.max(0.12, lit * 0.42)),
    deep:     hslHex(hue, Math.min(1, sat + 0.12), Math.max(0.16, lit * 0.55)),
    lite:     hslHex(hue, sat * 0.35, Math.min(0.94, lit + 0.30)),
    point:    hslHex(hue, Math.min(1, sat + 0.10), Math.max(0.14, lit * 0.40)),
    innerEar: hslHex(345, 0.45, 0.78),
    nose:     hslHex(350, 0.55, 0.74),
    eyeL:     hslHex(eyeL, 0.80, 0.55),
    eyeR:     hslHex(eyeR, 0.80, 0.55),
  };
}

const NAMES = [
  'Mochi', 'Biscuit', 'Pixel', 'Noodle', 'Pumpkin', 'Mittens', 'Waffle', 'Pepper',
  'Suki', 'Tofu', 'Bandit', 'Clementine', 'Gizmo', 'Hazel', 'Jasper', 'Luna',
  'Maple', 'Nimbus', 'Olive', 'Pip', 'Quill', 'Ruckus', 'Saffron', 'Tilly',
  'Ziggy', 'Bean', 'Cosmo', 'Dumpling', 'Ember', 'Figaro', 'Goose', 'Hobbes',
  'Indigo', 'Juniper', 'Kettle', 'Lychee', 'Marble', 'Nougat', 'Onyx', 'Pebble',
  'Mango', 'Smudge', 'Truffle', 'Widget', 'Yuzu', 'Zucchini', 'Biscotti', 'Comet',
];

const BREEDS: Record<string, string[]> = {
  solid:   ['Domestic Shorthair', 'Bombay', 'Russian Blue', 'Korat'],
  tabby:   ['Tabby', 'American Shorthair', 'Egyptian Mau', 'Toyger'],
  tuxedo:  ['Tuxedo', 'Domestic Shorthair'],
  bicolor: ['Turkish Van', 'Cornish Rex', 'Domestic Shorthair'],
  calico:  ['Calico', 'Japanese Bobtail', 'Aegean'],
  pointed: ['Siamese', 'Ragdoll', 'Birman', 'Himalayan'],
  spotted: ['Bengal', 'Ocicat', 'Savannah'],
};

/** Derive a breed archetype from pattern + build, picked deterministically. */
function deriveBreed(t: ResolvedTraits, seed: string): string {
  if (t.build.chonk >= 1.30) {
    const chonky = ['Maine Coon', 'British Shorthair', 'Norwegian Forest Cat', 'Ragamuffin'];
    return chonky[Math.floor(sampleUnit(seed, 'specimen.breed.chonky') * chonky.length)];
  }
  const bucket = BREEDS[t.coat.pattern] ?? BREEDS.solid;
  return bucket[Math.floor(sampleUnit(seed, 'specimen.breed') * bucket.length)];
}

/** Name + breed the cat, both derived deterministically from the seed. */
function deriveSpecimen(t: ResolvedTraits, seed: string): Specimen {
  const name = NAMES[Math.floor(sampleUnit(seed, 'specimen.name') * NAMES.length)];
  return { name, breed: deriveBreed(t, seed) };
}

/** The schema's defaults as plain values (d() knobs read as their midpoint). */
export const defaultConfig: CatsumConfig = resolveConfig(config);
